packages:
  - "apps/*"
  - "packages/*"
  - "tools/*"

allowBuilds:
  bigint-buffer: true
  bufferutil: true
  esbuild: true
  sharp: set this to true or false
  utf-8-validate: true
  workerd: set this to true or false

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
